import type { StaticImageData } from "next/image";

import beachImage from "@/assets/beach.png";
import classroomImage from "@/assets/classroom.png";
import marketImage from "@/assets/market.png";
import picnicImage from "@/assets/picnic.png";
import railwayImage from "@/assets/railway.png";

export type PictureDescription = Readonly<{
  image: StaticImageData;
  description: string;
}>;

export type PictureFilename =
  "beach.png" | "classroom.png" | "market.png" | "picnic.png" | "railway.png";

export const pictureDescriptions: Readonly<
  Record<PictureFilename, PictureDescription>
> = {
  "beach.png": {
    image: beachImage,
    description:
      "A wide, busy beach is shown during a friendly community clean-up on a bright, windy day. The foreground is covered with pale sand, scattered seaweed, shells, plastic bottles, cans, cups, wrappers, and other litter. At the lower left, a girl in a pink cap, purple T-shirt, denim shorts, gloves, and trainers uses a long litter picker to lift a plastic bottle beside a large blue recycling bag. Near the centre, a boy in a green shirt and a girl in a yellow shirt smile as they work together to carry a heavy green rubbish bag filled with collected waste. In front of them, a woman wearing a broad straw hat, light-blue shirt, dark trousers, white shoes, and blue gloves crouches on the sand and gestures toward a small crab. A young boy in a blue-and-white striped shirt crouches opposite her and looks carefully at the crab. At the lower right, large yellow and red bags are filled with bottles and cans, while a clear bag contains seaweed and natural beach debris. Several other children and adults spread across the sand, wearing gloves and collecting rubbish by hand or with litter grabbers. A man in a green shirt holds open a blue bag while a boy beside him uses a grabber. Another volunteer kneels near the water, and a group works beneath a blue canopy farther along the beach. The clean-up is taking place alongside ordinary beach activities: two children build a detailed sandcastle with buckets, people swim and play in the shallow water, surfers carry yellow boards, and others stand or walk at the water's edge. On the right, a lifeguard in a yellow shirt, red shorts, red cap, and sunglasses watches the sea through binoculars. He stands beside a wooden lifeguard tower and beneath a red-and-yellow safety flag. Small white waves roll toward the shore, and a red-and-white fishing boat travels across the blue water offshore. Several large gulls fly across the sky, with smaller birds in the distance. A straw sunhat with a red ribbon has been caught by the wind and is blowing high above the beach. In the background, rocky cliffs curve around the coastline, with palm trees, paths, railings, and rows of light-coloured houses overlooking the sea. The overall scene shows cooperation, environmental responsibility, beach safety, wildlife, windy weather, and many simultaneous actions.",
  },
  "classroom.png": {
    image: classroomImage,
    description:
      "A lively school science fair fills a large, sunlit hall with students, teachers, parents, experiments, and handmade models. In the centre foreground, a model volcano stands on a landscaped base of moss, stones, and small plants. Thick pink and orange foam is flowing dramatically down its dark sides, and five children in blue, green, and yellow school shirts lean toward it with wide eyes, open mouths, smiles, and surprised expressions. Behind the volcano, a boy reaches up to adjust a blue planet on a large black solar-system display. The display contains a bright orange sun, orbit lines, and several coloured planets suspended on rods. Above and behind it, oversized models of planets and small stars hang against a dark-blue curtain, and colourful triangular bunting stretches across the stage area. In the lower-left foreground, a student operates or examines a white-and-black wheeled robot with a mechanical arm and claw. The table around the robot contains wires, wooden pieces, notebooks, a pencil, a horseshoe magnet, magnifying glasses, leaves, a cut section of a tree branch, gears, small metal parts, and drawing or measuring tools. At the lower right, two girls smile and talk while studying seedlings growing in several transparent cups of dark soil. Some seedlings stand upright with green leaves, while others bend or curl. A leafy branch and an open observation sheet lie beside them. In the middle right, a teacher in a patterned blue-and-white outfit bends down thoughtfully to inspect a lightweight bridge model made from many thin sticks. The bridge spans between two grey supports, and nearby children handle a small machine with visible gears. Behind the bridge, a girl presents a miniature landscape containing trees, grass, paths, and a blue pond or river to two smiling adults. Around the room, students gather at additional tables to present plants, models, and experiments. Several parents on the left hold up mobile phones to photograph or record the projects. A girl in a pale-blue uniform stands near another display, while groups of children and adults talk in the background. Large windows along the left wall let in warm daylight and show green trees outside. Tall indoor plants add greenery around the room. The scene contains examples of chemistry, astronomy, robotics, engineering, biology, plant growth, observation, teamwork, presentation, curiosity, excitement, and family participation.",
  },
  "market.png": {
    image: marketImage,
    description:
      "A colourful open-air community market is crowded with shoppers, vendors, fresh food, flowers, and fabric-covered stalls on a warm, sunny morning. Large red, blue, yellow, cream, and green canopies create shade over the stone-paved market lane. In the left foreground, a woman wearing a long green patterned outfit carries two bunches of yellow bananas, one in each hand, as well as a large cream cloth shopping bag over her shoulder. She stands beside a banana stall and several baskets filled with shiny green and red apples. A few red apples have fallen from the display and rolled onto the ground beneath the wooden table. In the right foreground, a produce vendor wearing a blue shirt and beige apron smiles while weighing red tomatoes on a metal balance scale for a woman in a yellow patterned outfit. A small boy in a blue-and-white striped shirt stands next to the woman and points toward the produce. The stall is densely arranged with whole green watermelons, a large cut watermelon showing its red centre and black seeds, tomatoes, green beans, red and green peppers, carrots, cauliflower, leafy herbs, pineapple, apples, and other vegetables. At the bottom right, a metal fish counter displays several whole silver fish and orange salmon pieces on ice or a wet surface. A striped brown cat sits upright on the pavement in front of the fish, watching the stall attentively. In the centre, a market worker in a blue shirt and cap carries a green plastic crate packed with corn, carrots, tomatoes, and leafy vegetables. Behind him, a man with glasses holds a bunch of fresh herbs while speaking to an older woman who carries a woven basket full of vegetables. Buckets and crates of red, white, pink, orange, and yellow flowers form a bright flower stall between them. Other shoppers and vendors browse, talk, exchange goods, and arrange produce throughout the middle ground. At the far left, a helmeted cyclist waits beside a black bicycle near the entrance to the lane. More fruit and vegetable stalls continue into the background between warm cream and terracotta-coloured buildings. Trees cast dappled shadows over the street, old-fashioned lamps rise above the stalls, and several grey pigeons perch along a tiled rooftop. The scene offers details about buying and selling, quantities, colours, food groups, jobs, money, weighing goods, carrying objects, social interaction, animals, and the difference between foreground and background activity.",
  },
  "picnic.png": {
    image: picnicImage,
    description:
      "A large, green city park is full of families, children, animals, and outdoor activities on a day that is sunny in the foreground but becoming stormy in the distance. In the lower-right foreground, a family sits together on a red-and-white checked picnic blanket. The mother, wearing a blue patterned top and white trousers, smiles as she offers a bunch of purple grapes to a young boy in a blue-and-white striped shirt. The boy holds a slice of red watermelon. The father, wearing a green shirt and beige trousers, sits opposite them holding another watermelon slice. A woven picnic basket between them is filled with bananas, apples, grapes, oranges, and other fruit, with water bottles and cups nearby. A baby in a white shirt and pink trousers crawls off the edge of the blanket toward a loose orange resting on the grass. At the lower left, a girl in a coral shirt and jeans holds the kite reel while a boy in a yellow-and-white striped shirt reaches up to guide the string of a large red diamond-shaped kite flying high in the sky. A golden dog walks between the children and the picnic, pulling forward on its red lead and looking toward the family. In the centre of the lawn, a group of boys in colourful shirts plays football around a black-and-white ball. An older woman wearing a green blouse and a light sari uses a green watering can to water a circular flower bed filled with red, pink, yellow, orange, and white flowers. To the right, two boys kneel beside a red bicycle lying on the grass and examine or repair its chain or back wheel. In the background, a woman in pink and a man in blue jog side by side along a curved path. A gardener pushes a green wheelbarrow, and many other people stroll, exercise, stand, or play farther along the path. On the left, a calm pond contains numerous ducks swimming in different directions. Two people sit on a wooden bench facing the water. A white arched footbridge crosses part of the pond, and an open gazebo with a brown roof stands on the opposite bank. Willow trees, flowering bushes, neatly planted beds, lamp posts, and many leafy trees fill the park. Pale apartment buildings rise beyond the trees. The sky changes noticeably from soft blue with white clouds on the left to heavy, dark-grey storm clouds on the right, suggesting that rain may be approaching. The scene supports discussion of family relationships, food, games, exercise, gardening, helping, weather changes, locations, movement, and what might happen next.",
  },
  "railway.png": {
    image: railwayImage,
    description:
      "A bright, busy railway platform shows an affectionate family reunion while travellers arrive, depart, wait, and manage their luggage beside a long blue passenger train. In the centre foreground, a smiling boy in a yellow-and-white striped shirt, jeans, white trainers, and a large blue backpack runs forward with both arms stretched wide. An elderly man with grey hair and glasses kneels on one knee with his arms open, ready to embrace the child. He wears traditional light clothing under a brown sleeveless vest and looks delighted. A large green hard-shell suitcase stands near him, while a walking stick and a patterned scarf lie on the platform, suggesting that they may have slipped or been set down during the excited greeting. On the right, a man in a green polo shirt with a black backpack bends over a large upright blue suitcase and pushes or steadies it. A young girl wearing a pink shirt, jeans, red shoes, and a yellow backpack helps him from the other side. Behind them, a smiling woman in a pale floral outfit holds the hand and arm of an elderly man wearing glasses, a beige vest, and beige trousers as he carefully steps down from the train carriage. Several red, brown, and black duffel bags rest together on the platform, and a paper shopping bag contains a small green plant. On the left, a railway porter wearing a red uniform and red turban pushes a metal trolley stacked high with old brown, green, and red suitcases. Beside him, a man in glasses, a pale-blue shirt, and dark trousers checks his wristwatch while holding the handle of a small black rolling suitcase and carrying a shoulder bag. A large round analogue clock fixed to a roof column above him shows approximately ten minutes past ten. Along the middle of the platform, many passengers walk in both directions, stand near the carriage doors, carry bags, or talk to one another. Other travellers sit on benches beneath the station roof. Pigeons gather on the shiny tiled floor near the benches and around a decorative water fountain in the open area to the left. The long blue train has barred windows, carriage doors, a pale horizontal stripe, and one visible carriage number, but no clearly readable destination. A high metal roof with beams and columns covers the platform, while electrical lines and a footbridge extend above the tracks in the distance. Beyond the station are green trees, hills, scattered buildings, and a clear blue sky with soft clouds. The picture provides details about greetings, family generations, travel, time, luggage, jobs, helping older people, boarding and leaving a train, movement, anticipation, and spatial relationships.",
  },
};
