import { describe, expect, it } from "vitest";

import { adaptiveExerciseSchema } from "./adaptive-exercise.schema";
import { generatedAdaptiveExerciseSchema } from "./adaptive-exercise.schema";

const validExercise = {
  exerciseType: "choose_precise_word",
  prompt: "Choose the clearest description.",
  choices: ["A playful dog", "A dog quickly", "A dog play"],
  correctChoice: 0,
  hint: "Look for a word that describes the dog.",
  successMessage: "That adjective makes the scene vivid.",
  explanation: "Playful is an adjective that describes the dog.",
};

describe("adaptiveExerciseSchema", () => {
  it("removes option labels generated by the model", () => {
    const exercise = adaptiveExerciseSchema.parse({
      ...validExercise,
      choices: ["A. A playful dog", "B) A dog quickly", "C: A dog play"],
    });

    expect(exercise.choices).toEqual([
      "A playful dog",
      "A dog quickly",
      "A dog play",
    ]);
  });

  it("derives the correct index from the generated answer text", () => {
    const exercise = generatedAdaptiveExerciseSchema.parse({
      ...validExercise,
      correctChoice: undefined,
      correctAnswer: "A dog quickly",
    });

    expect(exercise.correctChoice).toBe(1);
  });

  it("rejects a generated answer that does not match a choice", () => {
    const result = generatedAdaptiveExerciseSchema.safeParse({
      ...validExercise,
      correctChoice: undefined,
      correctAnswer: "A sleeping cat",
    });

    expect(result.success).toBe(false);
  });

  it("rejects duplicate choices after normalisation", () => {
    const result = adaptiveExerciseSchema.safeParse({
      ...validExercise,
      choices: ["A. A playful dog", "B) A playful dog", "C. A dog play"],
    });

    expect(result.success).toBe(false);
  });
});
